import type { Metadata } from 'next'
import './globals.css'
import { Manrope, JetBrains_Mono } from 'next/font/google'

const manrope = Manrope({
	subsets: ['latin'],
	variable: '--font-manrope',
	display: 'swap',
	weight: ['400', '500', '600', '700'],
})

const jetbrains = JetBrains_Mono({
	subsets: ['latin'],
	variable: '--font-jetbrains',
	display: 'swap',
	weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
	title: 'Crypto blog',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${manrope.variable} ${jetbrains.variable} antialiased body`}
			>
				{children}
			</body>
		</html>
	)
}
